on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build
    steps:
        - name: Checkout
          uses: actions/checkout@v2.3.1
          
        - name: Setup Docker
          uses: docker-practice/actions-setup-docker@0.0.1
        
        - name: Init CUDA Submodule
          run: git submodule update --init

        - name: Enable Expermental For Squash, copy Nvidia repos and give scripts perms.
          run: |
            sudo chmod +X ./*.sh
            sudo cp ./cuda/dist/11.0/centos8-x86_64/base/cuda.repo ./cuda.repo
            sudo cp ./cuda/dist/11.0/centos8-x86_64/base/nvidia-ml.repo ./nvidia-ml.repo
            sudo cp ./daemon.json /etc/docker/daemon.json
            sudo systemctl restart docker 
                      
        - name: Build Nvidia CUDA Base
          uses: whoan/docker-build-with-cache-action@v5
          with: 
            image_name: nvidia/cuda
            push_image_and_stages: false
            dockerfile: ./cuda/dist/11.0/centos8-x86_64/base/Dockerfile
            image_tag: 11.0-base-centos8

        #- name: Slim Base CUDA Image
          #run: |
            #cd ./cuda/dist/11.0/centos8-x86_64/base/
            #curl https://downloads.dockerslim.com/releases/1.29.0/dist_linux.tar.gz -o dist_linux.tar.gz
            #docker images
            #tar -xf dist_linux.tar.gz
            #sudo chmod +x ./dist_linux/docker-slim
            #./dist_linux/docker-slim build --keep-perms --http-probe=false --continue-after=0 --tag=nvidia/cudaslim:11.0-base-centos8 nvidia/cuda:11.0-base-centos8          
            #cd ..//..//..//..//..//
  
        - name: Build Nvidia CUDA Runtime
          uses: whoan/docker-build-with-cache-action@v5
          with: 
            image_name: nvidia/cuda
            push_image_and_stages: false
            dockerfile: ./cuda/dist/11.0/centos8-x86_64/runtime/Dockerfile
            build_extra_args: --build-arg IMAGE_NAME=nvidia/cuda
            image_tag: 11.0-runtime-centos8
          
        - name: Build Main Image
          uses: whoan/docker-build-with-cache-action@v5
          with: 
            image_name: local/adoptopenjdk14-cuda-openj9xl-centos
            push_image_and_stages: false
            dockerfile: ./Dockerfile
            build_extra_args: --squash --compress
          
        #- name: Run the local Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
          #uses: anchore/scan-action@master
          #with:
            #image-reference: "local/adoptopenjdk14-cuda-openj9xl-centos-slim"
            #dockerfile-path: "Dockerfile"
            #acs-report-enable: true
            #include-app-packages: true
            #debug: true 
          
        #- name: Upload Anchore Scan Report
          #uses: github/codeql-action/upload-sarif@v1
          #with:
            #sarif_file: results.sarif
          
        - name: Upload Docker file
          run: |
            docker tag local/adoptopenjdk14-cuda-openj9xl-centos bgidiere/adoptopenjdk14-cuda-openj9xl-centos-slim
            docker push bgidiere/adoptopenjdk14-cuda-openj9xl-centos-slim:latest
            
            


            
