on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build
    steps:
        - name: Checkout
          uses: actions/checkout@v2.3.1
          
        - name: setup-docker
          uses: docker-practice/actions-setup-docker@0.0.1
        - name: Build docker images using cache
          uses: whoan/docker-build-with-cache-action@v5
          with: 
            image_name: local/adoptopenjdk14-cuda-openj9xl-centos       
        - name: Build Project
          run: |
            curl https://downloads.dockerslim.com/releases/1.29.0/dist_linux.tar.gz -o dist_linux.tar.gz
            docker images
            tar -xf dist_linux.tar.gz
            sudo chmod +x ./dist_linux/docker-slim
            sudo ./dist_linux/docker-slim build --http-probe=false --continue-after=0 local/adoptopenjdk14-cuda-openj9xl-centos:latest
            docker tag local/adoptopenjdk14-cuda-openj9xl-centos.slim:latest local/adoptopenjdk14-cuda-openj9xl-centos-slim:latest
        - name: Run the local Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
          uses: anchore/scan-action@master
          with:
            image-reference: "local/adoptopenjdk14-cuda-openj9xl-centos-slim:latest"
            dockerfile-path: "Dockerfile"
            acs-report-enable: true
            include-app-packages: true
            debug: true 
        - name: Upload Anchore Scan Report
          uses: github/codeql-action/upload-sarif@v1
          with:
            sarif_file: results.sarif
        - name: Upload Docker file
          run: |
            docker tag local/adoptopenjdk14-cuda-openj9xl-centos-slim bgidiere/adoptopenjdk14-cuda-openj9xl-centos-slim
            docker push bgidiere/adoptopenjdk14-cuda-openj9xl-centos-slim:latest
            
            


            
