on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build
    steps:
        - name: Checkout
          uses: actions/checkout@v2.3.1
          
        - name: setup-docker
          uses: docker-practice/actions-setup-docker@0.0.1
          
        - name: Build Project
          run: |
            cd ..//
            docker build ./java-openjdk-gpu -t bgidiere/adoptopenjdk14-cuda-openj9xl-centos-slim-local
            curl https://downloads.dockerslim.com/releases/1.29.0/dist_linux.tar.gz -o dist_linux.tar.gz
            tar -xf dist_linux.tar.gz
            sudo chmod +x ./dist_linux/docker-slim
            sudo ./dist_linux/docker-slim build bgidiere/adoptopenjdk14-cuda-openj9xl-centos-slim-local:latest --http-probe=false --continue-after
            cd java-openjdk-gpu
        - name: Run the local Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
          uses: anchore/scan-action@master
          with:
            image-reference: "bgidiere/adoptopenjdk14-cuda-openj9xl-centos-slim-local.slim"
            dockerfile-path: "Dockerfile"
            acs-report-enable: true
        - name: Upload Anchore Scan Report
          uses: github/codeql-action/upload-sarif@v1
          with:
            sarif_file: results.sarif
        - name: Upload Docker file
          run: |
            docker tag bgidiere/adoptopenjdk14-cuda-openj9xl-centos-slim-local.slim bgidiere/adoptopenjdk14-cuda-openj9xl-centos-slim
            docker push bgidiere/adoptopenjdk14-cuda-openj9xl-centos-slim:latest
            
            


            
